config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/404',                       to: 'errors#not_found'
  get    '/422',                       to: 'errors#unacceptable'
  get    '/500',                       to: 'errors#internal_error'
  get    '/favicon.ico',               to: redirect('/favicon.svg')
  get    '/favicon.svg',               to: 'assets#favicon'

  mount TheBoard::ApiV1 => '/api/v1'

  get    '/invite/:code',              to: 'profile#accept_invite', as: 'accept_invite'
  get    '/profile/new',               to: 'profile#new', as: 'new_profile'
  get    '/profile',                   to: 'profile#redirect_to_user'
  post   '/profile',                   to: 'profile#create'
  get    '/profile/edit',              to: 'profile#edit'
  patch  '/profile',                   to: 'profile#update'
  get    '/profile/username',          to: redirect('/settings')
  patch  '/profile/username',          to: 'profile#update_username'

  get    '/login',                     to: 'session#login'
  post   '/login',                     to: 'session#check_login'
  post   '/logout',                    to: 'session#logout'
  get    '/password',                  to: redirect('/settings')
  patch  '/password',                  to: 'session#update_password'

  get    '/settings',                  to: 'settings#show'

  get    '/invites',                   to: redirect('/settings')
  post   '/invites',                   to: 'invites#create'
  get    '/invites/:id',               to: redirect('/settings'), as: 'invite'
  delete '/invites/:id',               to: 'invites#destroy'

  get    '/users/:username',           to: 'users#show', as: 'user'
  post   '/users/:username/ban',       to: 'users#ban', as: 'ban_user'
  post   '/users/:username/unban',     to: 'users#unban', as: 'unban_user'

  root                                     'posts#index'
  get    '/posts',                     to: redirect('/')
  get    '/posts/new',                 to: 'posts#new', as: 'new_post'
  post   '/posts',                     to: 'posts#create'
  get    '/posts/:id',                 to: 'posts#show', as: 'post'
  get    '/posts/:id/edit',            to: 'posts#edit', as: 'edit_post'
  patch  '/posts/:id',                 to: 'posts#update'
  delete '/posts/:id',                 to: 'posts#destroy'

  get    '/posts/:id/comments',        to: 'post_comments#redirect_to_post', as: 'post_comments'
  post   '/posts/:id/comments',        to: 'post_comments#create'

  get    '/tags',                      to: 'tags#index'
  get    '/tags/new',                  to: 'tags#new', as: 'new_tag'
  post   '/tags',                      to: 'tags#create'
  get    '/tags/:slug',                to: redirect('/tags'), as: 'tag'
  delete '/tags/:slug',                to: 'tags#destroy'
end

app/models/invite.rb
# frozen_string_literal: true

class Invite < ApplicationRecord
  validates :code, :expires, presence: true
  belongs_to :created_by, class_name: 'User'
  belongs_to :claimed_by, class_name: 'User', optional: true

  def expires_str = format_date(expires)
  def claimed_at_str = claimed_by ? format_date(claimed_by.created_at_str) : 'Unclaimed'
end

app/controllers/invites_controller.rb
# frozen_string_literal: true

class InvitesController < ApplicationController
  # GET /invites is not routed (see SettingsController#show)

  # POST /invites
  def create
    Invite.create!(
      code:       generate_code,
      created_by: @authenticated_user,
      expires:    Rails.configuration.x.invite_expire_after.from_now
    )
    redirect_to settings_url
  end

  # DELETE /invites/:id
  def destroy
    @authenticated_user.created_invites.find(params[:id]).destroy
    redirect_to settings_url
  end

  private

  def generate_code = Base32.encode(SecureRandom.random_bytes(10))
end

app/views/invites/_invite.html.haml
.invite
  .watermark
    = render 'brand_icon_svg'
  .cap
    %p
      Br Br Br 
  .code
    .container
      .label 
        %span{ class: 'the-board' } The Board
        Invite:
      .value= invite.code
  .perforation
  .expires
    .container
      .label Expires:
      .value= invite.expires_str
  .cap.end
    %p 
      Br Br Br
    

app/views/invites/_invite_claimed.html.haml
.invite.claimed
  .value
    = link_to invite.claimed_by, class: 'nodecor' do
      .minicon
    = link_to invite.claimed_by
  .claimed-at
    .watermark
      = render 'brand_icon_svg'
    .container
      .label Claimed:
      .value= invite.claimed_at_str

app/views/invites/_invite_unclaimed.html.haml
.invite
  .watermark
    = render 'brand_icon_svg'
  = copy_to_clipboard_button '', accept_invite_url(invite.code), class: 'icon-only copy', title: 'Copy invite'
  .code
    .container
      .label 
        %span{ class: 'the-board' } The Board
        Invite:
      .value= invite.code
  .perforation
  .expires
    .container
      .label Expires:
      .value= invite.expires_str
  = button_to '', invite_path(invite), method: 'delete', class: 'icon-only close', title: 'Delete invite'