config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/404',                       to: 'errors#not_found'
  get    '/422',                       to: 'errors#unacceptable'
  get    '/500',                       to: 'errors#internal_error'
  get    '/favicon.ico',               to: redirect('/favicon.svg')
  get    '/favicon.svg',               to: 'assets#favicon'

  mount TheBoard::ApiV1 => '/api/v1'

  get    '/invite/:code',              to: 'profile#accept_invite', as: 'accept_invite'
  get    '/profile/new',               to: 'profile#new', as: 'new_profile'
  get    '/profile',                   to: 'profile#redirect_to_user'
  post   '/profile',                   to: 'profile#create'
  get    '/profile/edit',              to: 'profile#edit'
  patch  '/profile',                   to: 'profile#update'
  get    '/profile/username',          to: redirect('/settings')
  patch  '/profile/username',          to: 'profile#update_username'

  get    '/login',                     to: 'session#login'
  post   '/login',                     to: 'session#check_login'
  post   '/logout',                    to: 'session#logout'
  get    '/password',                  to: redirect('/settings')
  patch  '/password',                  to: 'session#update_password'

  get    '/settings',                  to: 'settings#show'

  get    '/invites',                   to: redirect('/settings')
  post   '/invites',                   to: 'invites#create'
  get    '/invites/:id',               to: redirect('/settings'), as: 'invite'
  delete '/invites/:id',               to: 'invites#destroy'

  get    '/users/:username',           to: 'users#show', as: 'user'
  post   '/users/:username/ban',       to: 'users#ban', as: 'ban_user'
  post   '/users/:username/unban',     to: 'users#unban', as: 'unban_user'

  root                                     'posts#index'
  get    '/posts',                     to: redirect('/')
  get    '/posts/new',                 to: 'posts#new', as: 'new_post'
  post   '/posts',                     to: 'posts#create'
  get    '/posts/:id',                 to: 'posts#show', as: 'post'
  get    '/posts/:id/edit',            to: 'posts#edit', as: 'edit_post'
  patch  '/posts/:id',                 to: 'posts#update'
  delete '/posts/:id',                 to: 'posts#destroy'

  get    '/posts/:id/comments',        to: 'post_comments#redirect_to_post', as: 'post_comments'
  post   '/posts/:id/comments',        to: 'post_comments#create'

  get    '/tags',                      to: 'tags#index'
  get    '/tags/new',                  to: 'tags#new', as: 'new_tag'
  post   '/tags',                      to: 'tags#create'
  get    '/tags/:slug',                to: redirect('/tags'), as: 'tag'
  delete '/tags/:slug',                to: 'tags#destroy'
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :authenticate_session, only: [:login, :check_login]

  # GET /login
  def login
    redirect_to root_url if session.key?(:user_id)
  end

  # POST /login
  def check_login
    username, password = params.require(:user).values_at(:username, :password)
    validation_error = nil

    if username.empty?
      validation_error = I18n.t('session.missing_username')
    elsif password.empty?
      validation_error = I18n.t('session.missing_password')
    else
      @authenticated_user = User.find_and_authenticate(username, password)
      if !@authenticated_user
        validation_error = I18n.t('session.bad_credentials')
      elsif @authenticated_user.banned?
        validation_error = I18n.t('session.account_disabled')
      else
        session_setup
        redirect_to root_url
        return
      end
    end
    flash[:notice] = validation_error
    flash[:username] = username
    redirect_to login_url
  end

  # PATCH /password
  def update_password
    if @authenticated_user.authenticate(params[:user][:old_password])
      @success = @authenticated_user.update(settings_pwchange_params)
    else
      @success = false
      @authenticated_user.errors.add(:old_password, I18n.t('errors.messages.incorrect'))
    end
  end

  # POST /logout
  def logout
    reset_session
    redirect_to login_url
  end

  private

  # TODO: centralize this logic
  def session_setup
    reset_session
    session[:user_id] = @authenticated_user.id
    session[:auth_iss] = Time.now.tv_sec
    session[:auth_exp] = (Time.now + Rails.configuration.x.session_expire_after).tv_sec
  end

  def settings_pwchange_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/session/_password_form.html.haml
= form_for @authenticated_user, namespace: 'password', url: password_path, html: {class: 'sm-container'} do |f|
  .field
    = f.label :old_password, 'Old Password'
    = f.password_field :old_password, required: true
    = f.errors_for :old_password
  .field
    = f.label :password, 'New Password'
    = f.password_field :password, required: true, minlength: 8
    = f.errors_for :password
  .field
    = f.label :password_confirmation, 'Re-Type Password'
    = f.password_field :password_confirmation, required: true, minlength: 8
    = f.errors_for :password_confirmation
  -# TODO: the success class should go away if the form is interacted with
  .actions{class: class?(success: @success)}
    = f.button 'Change Password'

app/views/session/login.html.haml
= form_tag '/login', class: 'sm-container' do
  .field
    = label :user, :username
    = text_field :user, :username, value: flash[:username], required: true, autofocus: true
  .field
    = label :user, :password
    = password_field :user, :password, required: true
  .errors
    - if notice
      .icon.auth-failure= notice
  .actions
    = button_tag 'Login'

app/views/session/update_password.html.haml
= turbo_frame_tag 'password_form' do
  = render 'password_form'