config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/404',                       to: 'errors#not_found'
  get    '/422',                       to: 'errors#unacceptable'
  get    '/500',                       to: 'errors#internal_error'
  get    '/favicon.ico',               to: redirect('/favicon.svg')
  get    '/favicon.svg',               to: 'assets#favicon'

  mount TheBoard::ApiV1 => '/api/v1'

  get    '/invite/:code',              to: 'profile#accept_invite', as: 'accept_invite'
  get    '/profile/new',               to: 'profile#new', as: 'new_profile'
  get    '/profile',                   to: 'profile#redirect_to_user'
  post   '/profile',                   to: 'profile#create'
  get    '/profile/edit',              to: 'profile#edit'
  patch  '/profile',                   to: 'profile#update'
  get    '/profile/username',          to: redirect('/settings')
  patch  '/profile/username',          to: 'profile#update_username'

  get    '/login',                     to: 'session#login'
  post   '/login',                     to: 'session#check_login'
  post   '/logout',                    to: 'session#logout'
  get    '/password',                  to: redirect('/settings')
  patch  '/password',                  to: 'session#update_password'

  get    '/settings',                  to: 'settings#show'

  get    '/invites',                   to: redirect('/settings')
  post   '/invites',                   to: 'invites#create'
  get    '/invites/:id',               to: redirect('/settings'), as: 'invite'
  delete '/invites/:id',               to: 'invites#destroy'

  get    '/users/:username',           to: 'users#show', as: 'user'
  post   '/users/:username/ban',       to: 'users#ban', as: 'ban_user'
  post   '/users/:username/unban',     to: 'users#unban', as: 'unban_user'

  root                                     'posts#index'
  get    '/posts',                     to: redirect('/')
  get    '/posts/new',                 to: 'posts#new', as: 'new_post'
  post   '/posts',                     to: 'posts#create'
  get    '/posts/:id',                 to: 'posts#show', as: 'post'
  get    '/posts/:id/edit',            to: 'posts#edit', as: 'edit_post'
  patch  '/posts/:id',                 to: 'posts#update'
  delete '/posts/:id',                 to: 'posts#destroy'

  get    '/posts/:id/comments',        to: 'post_comments#redirect_to_post', as: 'post_comments'
  post   '/posts/:id/comments',        to: 'post_comments#create'

  get    '/tags',                      to: 'tags#index'
  get    '/tags/new',                  to: 'tags#new', as: 'new_tag'
  post   '/tags',                      to: 'tags#create'
  get    '/tags/:slug',                to: redirect('/tags'), as: 'tag'
  delete '/tags/:slug',                to: 'tags#destroy'
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  # GET /settings
  def show
    @unclaimed_invites = @authenticated_user.created_invites.where(claimed_by: nil)
    @claimed_invites = @authenticated_user.created_invites.where.not(claimed_by: nil)
    @sections_visible = {}
    @themes = Theme.all
  end
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
  def new_invite_button(name)
    button_tag(name, name: nil, type: nil, data: {
      controller: 'invite',
      action:     'invite#new',
    })
  end

  def sections_bottom(sections_visible, height:)
    visible_sections = sections_visible.select {|_, v| v }
    visible_sections.each_with_index.to_h do |(k, _), i|
      [k, (visible_sections.length - i - 1) * height]
    end
  end
end

app/views/settings/_about.html.haml
%p
  %em The Board
  version:
  = Manifest.version + '.'
%p
  Copyright &copy; 2023 Coldwater Systems.
%p
  This program is free software: you can redistribute it and/or modify it under the terms of
  = link_to('AGPL', '/LICENSE') + ','
  version 3 only. The source code and issue tracker for
  %em The Board
  can be found
  = link_to('on GitLab', Manifest.source_code_url) + '.'
-# TODO: should probably list all the licensed components we're using
%p
  Unless otherwise mentioned, user contributions are licensed under
  = link_to('CC-BY-SA 4.0', 'http://creativecommons.org/licenses/by-sa/4.0/') + '.'

app/views/settings/_section.html.haml
- if @sections_visible.fetch(heading)
  %h2.section-header{style: "bottom:#{@sections_bottom.fetch(heading)}px"}=t "settings.section.#{heading}"
  %section= yield

app/views/settings/_user_tree.html.haml
= link_to user
- unless user.flags.empty?
  = "(#{user.flags})"
- if user.invited_users.any?
  %ul
    - user.invited_users.each do |user|
      %li= render 'user_tree', user: user

app/views/settings/show.html.haml
- @sections_visible['theme'] = true
- @sections_visible['username'] = true
- @sections_visible['password'] = true
- @sections_visible['invites'] = @authenticated_user.can_invite?
- @sections_visible['claimed_invites'] = @authenticated_user.can_invite? && @claimed_invites.any?
- @sections_visible['about'] = true
- @sections_visible['moderator_tools'] = @authenticated_user.moderator?
- @sections_visible['operator_tools'] = @authenticated_user.operator?
- @sections_bottom = sections_bottom(@sections_visible, height: 50)

.sections
  = render 'section', heading: 'theme' do
    .themes
      = render @themes

  = render 'section', heading: 'username' do
    = turbo_frame_tag 'username_form' do
      = render 'profile/username_form'

  = render 'section', heading: 'password' do
    = turbo_frame_tag 'password_form' do
      = render 'session/password_form'

  = render 'section', heading: 'invites' do
    .form.sm-container
      - if @unclaimed_invites.any?
        = render partial: 'invites/invite_unclaimed', collection: @unclaimed_invites, as: :invite
      - else
        No invites yet.
      .actions
        = button_to 'New Invite', invites_path

  = render 'section', heading: 'claimed_invites' do
    = render partial: 'invites/invite_claimed', collection: @claimed_invites, as: :invite
  
  = render 'section', heading: 'about' do
    .container
      = render 'about'

  = render 'section', heading: 'moderator_tools' do
    .container
      %h3 User Tree
      %ul
        - User.where(invited_by: nil).each do |user|
          %li= render 'user_tree', user: user

  = render 'section', heading: 'operator_tools' do
    .container
      %h3= link_to 'Tags list', tags_path
      %h3 Perf Counters
      %ul
        - PerfCounter.order(name: :asc).each do |counter|
          %li= "#{counter.name}: #{counter.value}"