config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/404',                       to: 'errors#not_found'
  get    '/422',                       to: 'errors#unacceptable'
  get    '/500',                       to: 'errors#internal_error'
  get    '/favicon.ico',               to: redirect('/favicon.svg')
  get    '/favicon.svg',               to: 'assets#favicon'

  mount TheBoard::ApiV1 => '/api/v1'

  get    '/invite/:code',              to: 'profile#accept_invite', as: 'accept_invite'
  get    '/profile/new',               to: 'profile#new', as: 'new_profile'
  get    '/profile',                   to: 'profile#redirect_to_user'
  post   '/profile',                   to: 'profile#create'
  get    '/profile/edit',              to: 'profile#edit'
  patch  '/profile',                   to: 'profile#update'
  get    '/profile/username',          to: redirect('/settings')
  patch  '/profile/username',          to: 'profile#update_username'

  get    '/login',                     to: 'session#login'
  post   '/login',                     to: 'session#check_login'
  post   '/logout',                    to: 'session#logout'
  get    '/password',                  to: redirect('/settings')
  patch  '/password',                  to: 'session#update_password'

  get    '/settings',                  to: 'settings#show'

  get    '/invites',                   to: redirect('/settings')
  post   '/invites',                   to: 'invites#create'
  get    '/invites/:id',               to: redirect('/settings'), as: 'invite'
  delete '/invites/:id',               to: 'invites#destroy'

  get    '/users/:username',           to: 'users#show', as: 'user'
  post   '/users/:username/ban',       to: 'users#ban', as: 'ban_user'
  post   '/users/:username/unban',     to: 'users#unban', as: 'unban_user'

  root                                     'posts#index'
  get    '/posts',                     to: redirect('/')
  get    '/posts/new',                 to: 'posts#new', as: 'new_post'
  post   '/posts',                     to: 'posts#create'
  get    '/posts/:id',                 to: 'posts#show', as: 'post'
  get    '/posts/:id/edit',            to: 'posts#edit', as: 'edit_post'
  patch  '/posts/:id',                 to: 'posts#update'
  delete '/posts/:id',                 to: 'posts#destroy'

  get    '/posts/:id/comments',        to: 'post_comments#redirect_to_post', as: 'post_comments'
  post   '/posts/:id/comments',        to: 'post_comments#create'

  get    '/tags',                      to: 'tags#index'
  get    '/tags/new',                  to: 'tags#new', as: 'new_tag'
  post   '/tags',                      to: 'tags#create'
  get    '/tags/:slug',                to: redirect('/tags'), as: 'tag'
  delete '/tags/:slug',                to: 'tags#destroy'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  belongs_to :published, class_name: 'PostRevision', optional: true
  has_many :revisions, class_name: 'PostRevision'
  has_many :comments, class_name: 'PostComment'

  def published_at_str = format_datetime(published_at)
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /
  def index
    @posts = Post.where.not(published_id: nil).order(created_at: :desc)
    if params.key?(:before_id)
      @before_id = params[:before_id]
      @posts = @posts.where(id: ...@before_id)
    end

    @posts = @posts.limit(5)
  end

  # GET /posts/1
  def show
    @post_comments = @post.comments.order(created_at: :desc)
    @new_post_comment = PostComment.new
  end

  # GET /posts/new
  def new
    @post_revision = PostRevision.new
    @form_url = posts_path
  end

  # GET /posts/1/edit
  def edit
    raise Forbidden if @post.owner != @authenticated_user

    @post_revision = @post.revisions.last
    @form_url = post_path(@post)
  end

  # POST /posts
  def create
    @post = Post.create!(owner: @authenticated_user)
    @post_revision = PostRevision.new(**post_revision_params, post: @post, author: @authenticated_user)
    if @post_revision.save
      if params[:button] == 'publish'
        @post.published = @post_revision
        @post.published_at ||= Time.now
        @post.save!
        redirect_to root_url
      else
        redirect_to @post
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH /posts/1
  def update
    raise Forbidden if @post.owner != @authenticated_user

    @post_revision = PostRevision.new(**post_revision_params, post: @post, author: @authenticated_user)

    if @post_revision.save
      if params[:button] == 'publish'
        @post.published = @post_revision
        @post.published_at ||= Time.now
        @post.save!
        redirect_to root_url
      else
        redirect_to @post
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    raise Forbidden if @post.owner != @authenticated_user

    @post.transaction do
      @post.published = nil
      @post.save!
      @post.revisions.each(&:destroy)
      @post.comments.each(&:destroy)
      @post.destroy
    end
    redirect_to root_url
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_revision_params
    params.require(:post_revision).permit(:body)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def infinite_scroll_container(before_id:, &)
    if before_id
      turbo_frame_tag("infinite-scroll-#{before_id}", target: '_top', &)
    else
      yield
      nil
    end
  end

  def infinite_scroll_next(before_id:, &)
    turbo_frame_tag("infinite-scroll-#{before_id}",
                    src:     root_path(before_id:),
                    target:  '_top',
                    loading: 'lazy', &)
  end
end

app/views/posts/_comment.html.haml
.comment
  .metadata
    = render partial: 'users/small', locals: { user: comment.author }
    .date
      = comment.created_at_str
  %p= comment

app/views/posts/_comments.html.haml
.comments
  .comment-header
    %h2 Comments
    = new_comment_button 'New Comment', 'Discard', expander_id: 'new-comment-expander', class: 'icon new-message'
  #new-comment-expander
    = form_for @new_post_comment, html:{class: 'new-comment'} do |f|
      .field
        = f.text_area :text, required: true
        .right
          = f.button 'Post Comment', class: 'icon new-message'
      .horizontal.field
      = f.errors_for :text
  - if @post_comments.any?
    = render @post_comments
  - else
    .no-comments No comments yet.

app/views/posts/_form.html.haml
= form_for @post_revision, url: @form_url, html: {class: 'container'}  do |f|
  .field
    -# = f.label :body, 'New body'
    = f.rich_text_area :body, required: true
    = f.errors_for :body
  .actions
    = f.button 'Save Draft', value: 'save', class: 'outline'
    = f.button 'Publish', value: 'publish'

app/views/posts/_post.html.haml
.post
  .content
    = (post.published || post.revisions.last).body
  .bottom
    .metadata
      - if post.published
        .user
          = render partial: 'users/small', locals: { user: post.owner }
        .date
          = post.published_at_str
      - else
        .draft
          Draft
    %spacer
    .actions
      - if post.owner == @authenticated_user
        = button_to '', post_path(post), method: 'delete', class: 'outline icon-only trash', title: 'Delete post',
          data: {turbo_confirm: "Are you sure you want to delete this post?"}
        = link_to '', edit_post_path(post), class: 'outline button icon-only edit', title: 'Edit post'
      %span
        = link_to "#{post.comments.count}", post, class: 'button icon message', title: 'Comments'

app/views/posts/edit.html.haml
= render 'form'
= link_to 'Back', @post

app/views/posts/index.html.haml
= infinite_scroll_container(before_id: @before_id) do
  - unless @posts.empty?
    = render @posts, partial: 'post'
    = infinite_scroll_next(before_id: @posts.last.id) do
      .div(style='padding-bottom: 100px; text-align: center') Loading more posts...

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= render @post
= render 'comments'